final products = [
  {
    'id': '0',
    'title': 'Grey boots for men',
    'price': 57.07,
    'imageUrl': 'assets/images/shoes_1.webp',
    'company': 'Woodland',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Navy Boot for Men',
    'price': 70.25,
    'imageUrl': 'assets/images/shoes_2.webp',
    'company': 'Woodland',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Navy Sneakers',
    'price': 48.29,
    'imageUrl': 'assets/images/shoes_3.webp',
    'company': 'Woodland',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Camel boots',
    'price': 61.47,
    'imageUrl': 'assets/images/shoes_4.webp',
    'company': 'Woodland',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Camel Nubuk Oily Polished',
    'price': 57.07,
    'imageUrl': 'assets/images/shoes_5.webp',
    'company': 'Woodland',
    'sizes': [8, 9, 10,11],
  },
  {
    'id': '5',
    'title': 'Olive green sandal',
    'price': 52.67,
    'imageUrl': 'assets/images/shoes_6.webp',
    'company': 'Woodland',
    'sizes': [7,8, 9],
  },
];